version: '3'
services:
  fairyla:
    container_name: fairyla
    image: staugur/fairyla:latest
    restart: always
    ports:
      - "10210"
    environment:
      - fairyla_redis_url=redis://@redis:6379
      - fairyla_sapic_api=https://picbed.pro
      - fairyla_sapic_token=<Please Fill It>
      - fairyla_opentoken=<Please Fill It>
    network_mode: host
    volumes:
      - frontend:/fairyla/
volumes:
  frontend:
