name: Publish Release Asset
on:
  push:
    tags:
      - '*'
  release:
    types: [created]
jobs:
  release_asset:
    name: Publish Release Asset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Dependencies
      run: cd client && yarn --no-lockfile
    - name: Pack frontend and backend
      run: sh scripts/bump.sh pack
    - name: Upload dist to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: dist/fairyla*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
