name: Go Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: cd server && go test ./... -race -coverprofile=coverage.txt -covermode=atomic && bash <(curl -s https://codecov.io/bash)
      env:
        redis_url: redis://localhost
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
